### ISSUE TITLE
The security token could not be authenticated or authorized

### ISSUE THREAD

**Issue by aarizti** [difi/kontaktregisteret-klient#13]
Hi,

Some days ago we started experiencing issues in production when trying to use the contact registry, and we haven't been able to fix it yet.

The error is as follows:

```
org.apache.ws.security.WSSecurityException: The security token could not be authenticated or authorized
	at org.apache.ws.security.validate.SignatureTrustValidator.validate(SignatureTrustValidator.java:86) ~[wss4j-1.6.19.jar!/:1.6.19]
	at org.apache.ws.security.processor.SignatureProcessor.handleToken(SignatureProcessor.java:186) ~[wss4j-1.6.19.jar!/:1.6.19]
	at org.apache.ws.security.WSSecurityEngine.processSecurityHeader(WSSecurityEngine.java:402) ~[wss4j-1.6.19.jar!/:1.6.19]
	at org.apache.cxf.ws.security.wss4j.WSS4JInInterceptor.handleMessage(WSS4JInInterceptor.java:274) [cxf-rt-ws-security-2.7.3.jar!/:2.7.3]
```

We haven't made any change to our server app for about 5 months now, so it's unclear to us why this started to happen all of the sudden. It seems that we are able to send a retrieve contact request and we got something back from the server, but we are unsure as to whether the response is a valid one or not, and immediately after getting the response the error quoted happens.

Any help would be greatly appreciated
Regards.

**Comment by 3150ihe** [comment]
First - can you check you  virksomhetssertifikat. Is it still valid? If the certificate  is still valid, send a mail to idporten@difi.no. I need to know  exact when the  problem start. I have to know  your organaization number.
-ivar

**Comment by aarizti** [comment]
I double checked and we were having a problem related to our own project configuration - keystore alias for the environment.

Everything is working now.

Thanks @3150ihe , please feel free to close this.
